name: Merge translation from i18n to manifests files

on:
  pull_request:
    branches:
      - main

jobs:
  sync-changes-in-i18n:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Run script syncI18nToManifest & Commit changes
        run: |
          touch test.txt
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Update en-EN.json file based on manifest changes" || echo "No changes to commit"
          git push origin HEAD:${{ github.head_ref }}
